const paragraphs = [
    "I started developing software more than ten years ago. Since then, I've built many applications, created dozens of open source projects, and pushed thousands of commits. Besides that, I spoke in more than a hundred conferences, and had the opportunity to chat with a ton of developers along the way.",
    "These questions stayed on my head for a long time. I realized that I could buy the best mechanical keyboards, go to the most famous tech conferences in the world, and learn all the newest frameworks. Still, if I cultivated bad habits, it would be impossible to become a top developer. Because of that, I decided to reach out to the best developers I know and ask them tips on how to be more productive.",
    "If you've ever tried to lose weight, you know how frustrating that entire process is. You can exercise as hard as you can for three hours, but if you do that only once in a week, it will have zero effect on you. What truly generates results is when you go multiple times per week. Then suddenly, a few months later, you'll start noticing changes in your body.",
    "Habits are the compound interest of self-improvement. The same way that money multiplies through compound interest, the effects of your habits multiply as you repeat them. They seem to make little difference on any given day and yet the impact they deliver over the months and years can be enormous. It is only when looking back two, five, or perhaps ten years later that the value of good habits and the cost of bad ones becomes strikingly apparent.",
    "People will try to convince you which is the best OS, the best programming language, the best framework. They will tell you about all the amazing things that their tool does and that your tool does not. The reality though is that every single tool is different and we are also different as users. What is best for you, may not be the best for me or for others.",
    "It's crucial to understand that the noise will always be there. You don't need to necessarily abandon social media, unsubscribe from all newsletters, and stop watching YouTube videos. A digital detox can definitely help for a while; however, it’s not a long term solution. What you need to do is to cherry-pick what is relevant to you at this point in your career.",
    "Accept the fact that you simply can't learn everything. Remember, desires are endless; needs are limited. Accept the fact that newer is not always better. There are people working with ancient programming languages and still making a lot of money. Practice daily the subtle art of saying ‘no’. No to that newest library. No to that fancier platform. Say more 'noes' so you can say yes to what really matters to you.",
    "Another point to consider is how transferable the acquired knowledge can be. For example, learning Rust vs. Go: Two pretty distinct tools that are competing in the same problem space. Rust seems a lot cooler and sophisticated, but Go is very likely the language that’s gonna help you land a good job. In that case, I would personally optimize for the one that can help me reach the next step of my career.",
    "That entire semester had a great impact on me. Even more than 10 years later, I still remember all the HTML tags and CSS properties, because I had to manually write them without any further help. If I had forgotten even just one character, the entire thing wouldn’t work, so I needed to make sure that I completely understood what I was writing.",
    "The same applies to you. If you decide to become a great developer, it's important to understand core concepts such as algorithms, logic, network, accessibility, security, and user experience. You don’t necessarily need them to build your first app, but knowing them will help you build the next ten complex applications you will create in the future.",
    "For me personally, it all started with choosing the right Operating System (OS). At the time, I had a Windows machine, but everybody was telling me that Apple computers were better and I should switch. However, their prices were way out of my league, so getting one was not even a possibility. Fast forward a couple of years and one of my employers gave me the option to choose between Windows and MacOS. I went straight for the MacOS to see what the fuss was about and what was so incredible about it. After some time using MacOS, Ubuntu started to become very popular and everybody was telling me I should switch to Ubuntu. So I thought I'd give it a try and started using it. My point here is not to tell you which one you should choose, the point here is that there's no such thing as the best tool."
]